language: python
python:
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov


# command to run tests
script:
  - pytest tests.py --cov

# when done
after_success:
  - coveralls
